Sub CheckString()
row_number = 0
count_of_String = 0

Do
row_number = row_number + 1
item_in_review = Sheets("Cost sheet & SO").Range("A" & row_number)
item_in_review2 = Sheets("Cost sheet & SO").Range("B" & row_number)
item_in_review3 = Sheets("Cost sheet & SO").Range("C" & row_number)

    ' Project Manager Service
    If InStr(item_in_review, "Project Manager") Then
        Worksheets("Cost sheet & SO").Cells(row_number, 51).Value = "PMS"
        Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "PMS"
        Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "PMS"
        Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "PMS"
        Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "PMS"
        Worksheets("Cost sheet & SO").Clls(row_number + 5, 50).Value = "PMS"
        
    ' Service Desk
    ElseIf InStr(item_in_review, "Service Desk") Then
        Worksheets("Cost sheet & SO").Cells(row_number, 51).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SD"
        Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SD"
        
    ' Managed Service - OS : Implement Service
    ElseIf InStr(item_in_review2, "Implement Service") Then
        Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "MSOS"
        Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "Msos"
        
     ' Managed Service - OS :  OS Managed Service
    ElseIf InStr(item_in_review2, "OS Managed Service") Then
        Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "MSOS"
        Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "Msos"
        Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "Msos"
    'Back as a Service
    ElseIf InStr(item_in_review, "Backup as a Service") Then
        Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "BaaS"
        Worksheets("Cost sheet & SO").Cells(row_number + 16, 50).Value = "BaaS"
    ' Infrastructure
    ElseIf InStr(item_in_review2, "Infrastructure Manage") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "Router and Switch") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "Load Balance") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "Server and Storage") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "Security") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "Log") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "Two-Factor Authen(2FA)") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
    ElseIf InStr(item_in_review3, "VMware vCenter + Anti-Virus Trend Micro(Deep Security)") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Infra"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Infra"
 
    ' Security Service
    ElseIf InStr(item_in_review, "Security Service") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = ""
    ' Security Service :Vulnerability Assessment (IP or URL/Time)
    ElseIf InStr(item_in_review2, "Vulnerability Assessment (IP or URL/Time)") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "Secure"
    ' Security Service :Penetration Testing (IP or URL/Time)
    ElseIf InStr(item_in_review2, "Penetration Testing (IP or URL/Time)") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 16, 50).Value = "Secure"
      ' Security Service : Security Operation Center (SOC)
    ElseIf InStr(item_in_review2, "Security Operation Center (SOC) ") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Secure"
      ' Security Service : Log
    ElseIf InStr(item_in_review2, "Log") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Secure"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Secure"
         
    ' Managed Service - DBA
    ElseIf InStr(item_in_review, "Managed Service - DBA") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = ""
    ElseIf InStr(item_in_review2, "DBA") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "DBA"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "DBA"
    ' Managed Uipath RPA
    ElseIf InStr(item_in_review2, "License UiPath") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "RPA"
    ElseIf InStr(item_in_review2, "Manday and Implement") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "RPA"
    ElseIf InStr(item_in_review2, "MA Service") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "RPA"
    ElseIf InStr(item_in_review2, "Training") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "RPA"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "RPA"
    ElseIf InStr(item_in_review2, "SCG - Cloud Service") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 16, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 17, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 18, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 19, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 20, 50).Value = "SCG"
    ElseIf InStr(item_in_review, "Additional") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 16, 50).Value = "SCG"
        ElseIf InStr(item_in_review2, "Database as a Service on SCG Cloud") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 16, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 17, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 18, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 19, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 20, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 21, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 22, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 23, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 24, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 25, 50).Value = "SCG"
    ElseIf InStr(item_in_review2, "Backup as a Service on SCG - Cloud") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SCG"
    ElseIf InStr(item_in_review2, "SCG public - Cloud Service ") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 14, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 15, 50).Value = "SCG"
    ElseIf InStr(item_in_review2, "SCG public Database as a Service") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 8, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 9, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 10, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 11, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 12, 50).Value = "SCG"
         Worksheets("Cost sheet & SO").Cells(row_number + 13, 50).Value = "SCG"
    ElseIf InStr(item_in_review, "Other") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = ""
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Other"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Other"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Other"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Other"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Other"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Other"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Other"
    ElseIf InStr(item_in_review, "Trading") Then
         Worksheets("Cost sheet & SO").Cells(row_number, 50).Value = ""
         Worksheets("Cost sheet & SO").Cells(row_number + 1, 50).Value = "Trading"
         Worksheets("Cost sheet & SO").Cells(row_number + 2, 50).Value = "Trading"
         Worksheets("Cost sheet & SO").Cells(row_number + 3, 50).Value = "Trading"
         Worksheets("Cost sheet & SO").Cells(row_number + 4, 50).Value = "Trading"
         Worksheets("Cost sheet & SO").Cells(row_number + 5, 50).Value = "Trading"
         Worksheets("Cost sheet & SO").Cells(row_number + 6, 50).Value = "Trading"
         Worksheets("Cost sheet & SO").Cells(row_number + 7, 50).Value = "Trading"
    Else
    End If
Loop Until row_number = 450
End Sub

 
